#!/bin/bash

set -eou pipefail

ROOT_PATH=$1
DOMAIN=$2
REVERSE_IPV4_SUBNET=$3
NAMESERVER_IPV4_HOST=$4
NAMESERVER_IPV4_ADDRESS=$5
NAMESERVER_HOSTNAME=$6
OUTPUT_FWD_FILENAME=$7
OUTPUT_REV_FILENAME=$8

sed "s/DOMAIN_PLACEHOLDER/$DOMAIN/g" $ROOT_PATH/config/bind/fwd.DOMAIN_PLACEHOLDER.db > $ROOT_PATH/config/bind/$OUTPUT_FWD_FILENAME
sed "s/DOMAIN_PLACEHOLDER/$DOMAIN/g" $ROOT_PATH/config/bind/REVERSE_SUBNET_PLACEHOLDER.db > $ROOT_PATH/config/bind/$OUTPUT_REV_FILENAME

if [[ $(uname -s) == 'Linux' ]]; then
  sed -i "s/NAMESERVER_IPV4_ADDRESS_PLACEHOLDER/$NAMESERVER_IPV4_ADDRESS/g" $ROOT_PATH/config/bind/$OUTPUT_FWD_FILENAME
  sed -i "s/NAMESERVER_HOSTNAME_PLACEHOLDER/$NAMESERVER_HOSTNAME/g" $ROOT_PATH/config/bind/$OUTPUT_REV_FILENAME
  sed -i "s/NAMESERVER_IPV4_HOST_PLACEHOLDER/$NAMESERVER_IPV4_HOST/g" $ROOT_PATH/config/bind/$OUTPUT_REV_FILENAME
else
  # Mac :-(  Still better than Powershell or MSDOS Command Prompt
  sed -i '' "s/NAMESERVER_IPV4_ADDRESS_PLACEHOLDER/$NAMESERVER_IPV4_ADDRESS/g" $ROOT_PATH/config/bind/$OUTPUT_FWD_FILENAME
  sed -i '' "s/NAMESERVER_HOSTNAME_PLACEHOLDER/$NAMESERVER_HOSTNAME/g" $ROOT_PATH/config/bind/$OUTPUT_REV_FILENAME
  sed -i '' "s/NAMESERVER_IPV4_HOST_PLACEHOLDER/$NAMESERVER_IPV4_HOST/g" $ROOT_PATH/config/bind/$OUTPUT_REV_FILENAME
fi
